### ISSUE TITLE
lost internet : (

### ISSUE THREAD

**Issue by kaiju-dono** [uC-Manny/ku_fs_q4_2021_fp_staying_alert#23]
i'm adding this bc my internet went out right when i pressed create branch,  so when i got back, the branch was made but i don't have the CLI commands to initiate the local branch, i'm just using this to get those snippets. i'll delete this and the branch it makes after i get the snippets. sorry lol

**Comment by uC-Manny** [comment]
Such issues should not be addressed or discussed here, instead use e-mail or slack for such matters or simply reach out for help!
